site_name: MLVP Docs
site_url: http://mlvp-doc.readthedocs.io/
site_description: Multi-language Verilation Methodology Framework Documentation
site_author: BlueSpace, BOSC

repo_url: https://gitee.com/beifengzhishen955/mlvp-doc
edit_uri: blob/main/docs/

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: index.md
  - Installation: prepare.md
  - Quick Started: quickstart.md
  - Tutorial: tutorial.md
  - Developer Guide: developer.md
  - API: doxygen/html/
  - About: about.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: True
      baselevel: 2
  - pymdownx.arithmatex

extra_javascript:
  # other extra java script
  - static/mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

copyright: Copyright &copy; 2023 <a href="https://etogaosion.github.io">BlueSpace</a> @ <a href="https://www.bosc.ac.cn">Beijing Institute of Open Source Chip</a>
